### ISSUE TITLE
Bootstrapping the project (create-react-app)

### ISSUE THREAD

**Issue by smit2k14** [smit2k14/HyperQuestDA-frontend#1]
Nothing much, just use create react app to get a general format ready.

**Comment by AkMo3** [comment]
I would like to take this task

**Comment by smit2k14** [comment]
Hey. Fork this repo and create a PR after completing the task. It is simple enough so shouldn't be a problem.

**Comment by AkMo3** [comment]
I am not able to upload the node_modules at it has a lot of files of react-app. Please let me know how to work around with that
