### ISSUE TITLE
Front page asking to choose one of the given datasets

### ISSUE THREAD

**Issue by smit2k14** [smit2k14/HyperQuestDA-frontend#8]
a simple webpage which shows the available datasets and send a get request about the choice.

**Comment by AkMo3** [comment]
I would like to take this one.

**Comment by AkMo3** [comment]
Would it also be the Homepage?

**Comment by smit2k14** [comment]
Yeah this would be the homepage

**Comment by helloshantanu** [comment]
@smit2k14 dont u think 25 points are too less for a whole web page, i was checking out and found out that schooler repo just posted 150 points for developing a calender component

**Comment by smit2k14** [comment]
@helloshantanu that requires significant communication with backend as well. Do not worry about the point system, I'll be able to handle that. Also, if you haven't noticed, I haven't assigned the points yet. I'll do that once I see and review the PR.

**Comment by helloshantanu** [comment]
So isn't slop-25 represent point, I thought 25 is the points for points.

My bad

**Comment by RoneelV** [comment]
@helloshantanu 

> So isn't slop-25 represent point, I thought 25 is the points for points.
> 
> My bad

That label represents points based on estimated difficulty, actual points will be awarded later after PR is reviewed.
